### ISSUE TITLE
OGBV citation

### ISSUE THREAD

**Issue by mallory** [claucece/draft-celi-ipvc#10]
Quotable text from https://www.apc.org/sites/default/files/gender-cybersecurity-policy-litreview.pdf:

"Women and girls face specific cyber threats in the digital age that are considered forms of gender-based violence as they occur because of their gender, or because they disproportionately affect one gender. While this violence is mediated by digital technology, it is part of the same offline structural violence; but its technological dimension adds elements of search, persistence, replicability and scalability that facilitate the aggressors’ access to their targets and can exacerbate the harm."

**Comment by claucece** [comment]
added now ;)
