### ISSUE TITLE
Tactics citations

### ISSUE THREAD

**Issue by mallory** [claucece/draft-celi-ipvc#12]
To cite or to cross check against our list:

Emily Tseng, Rosanna Bellini, Nora McDonald, Matan Danos, Rachel Greenstadt, Damon McCoy, Nicola Dell, & Thomas Ristenpart (2020). The Tools and Tactics Used in Intimate Partner Surveillance: An Analysis of Online Infidelity Forums. CoRR, abs/2005.14341.

R. Chatterjee et al., "The Spyware Used in Intimate Partner Violence," 2018 IEEE Symposium on Security and Privacy (SP), San Francisco, CA, USA, 2018, pp. 441-458, doi: 10.1109/SP.2018.00061.

**Comment by claucece** [comment]
Added now!
