### ISSUE TITLE
Deepfakes

### ISSUE THREAD

**Issue by claucece** [claucece/draft-celi-ipvc#9]
Leonie notes:

```
Lastly, Deepfakes may be something worth accenting in the text.
```

**Comment by claucece** [comment]
@julianaguerra will take a look at the literature.

**Comment by julianaguerra** [comment]
I reviewed Witness reports and there appears only one case of a woman politcian in India who was victim of a deepfake. They mention there are many cases of deepfakes being used to harass mainly women, and many experts consider this scenario will increase at the same time GAN tools are popularized. I think it's maybe not necesary to go in depth on this explanation, and just added a shot mention at the intro section of whoy we are not including CSAM and deepfakes. Maybe it's necesary to better write it.

**Comment by claucece** [comment]
Agreed! I review the text and looks good!
